// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Runtime.InteropServices;

 
	public class MyiOSSharing: MonoBehaviour
	{
		#if UNITY_IOS && !UNITY_EDITOR
		[DllImport("__Internal")]
		public static extern void iOSShareImgAndMessage (string iosPath, string message);
		[DllImport("__Internal")]
		public static extern void iOSShareMessage (string message);
		#endif
	}


